### ISSUE TITLE
Sprite split area error

### ISSUE THREAD

**Issue by k8w** [bmarwane/spriteSplitter#2]
PNG:
![Rhythm Heaven Fever-cellanim.t_爱给网_aigei_com (4).png](https://i.loli.net/2017/12/13/5a309a7cab0d8.png)

**Expect**
Split by each black grid

**Actual**
![2.png](https://i.loli.net/2017/12/13/5a309a7ca98a2.png)

The bottom area are not splitted, but be treated as a whole part.

**Comment by bmarwane** [comment]
Hi,
as stated in the app's main screen, the top left pixel is used as a reference to detect individual frames.
basically, the script looks for each group of pixels that are completely surrounded by the likes of the reference pixel ( in your example, a black pixel)

with that been said, after I zoomed into the image you provided, I noticed that the color of the grid is not always black ( see the image below )

![pixels](https://user-images.githubusercontent.com/1775843/34182275-784530d6-e50d-11e7-94a7-3b7e7754d6a6.png)

after unifying the grid color with gimp, the problem seems to be solved.

![solved](https://user-images.githubusercontent.com/1775843/34183174-539513d8-e511-11e7-8058-e3f009605cb6.png)
