### ISSUE TITLE
No text on Linux

### ISSUE THREAD

**Issue by Pollito001** [bmarwane/spriteSplitter#3]
Im using manjaro Linux, When i trying to open an image the window show without text
![spritesplitter](https://user-images.githubusercontent.com/4990486/61190203-b5e3f000-a666-11e9-99f4-0cb771605432.png)

**Comment by bmarwane** [comment]
ow! that's scary,

i digged a little into the problem and found an issue regarding how electron choose a default font in linux:

[https://github.com/electron/electron/issues/1605](https://github.com/electron/electron/issues/1605)

I think that i need to updage electron version and recompile some new binaries ( i suppose that the issue must be fixed in the current version of electron)

I will try to do this ASAP

**Comment by Pollito001** [comment]
@bmarwane  Thanks for this great tool, Ill be waiting for any progress.

**Comment by Pollito001** [comment]
@bmarwane You right, Updating electron version and recompile fix the issue for me. ;).
